const Controller = require('$controllers');

module.exports = [
    /**
     * @generator route generated by kraaken-cli
     * @Route : /url
     * @Method : get
     */
    {
        url: "/importxls",
        method: "get",
        func: [Controller['FileController@updateXls']],
        functionName: 'update',
        //perm: ['*']
    },

];
